=== crkn-rcdr/Access-Platform/Databases/dipstaging.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/crkn-rcdr/Access-Platform/blob/master/Databases/dipstaging.schema.json",
  "title": "dipstaging Document Schema",
  "description": "dipstaging documents are generated for every AIP in the legacy preservation platform. They imply the availability of an AIP for import into the access platform.",
  "type": "object",
  "properties": {
    "_id": {
      "description": "Legacy preservation platform AIP ID",
      "type": "string"
    },
    "_rev": { "$ref": "./_util.schema.json#/definitions/_rev" },
    "slug": {
      "description": "Access slug chosen when DIP is smelted",
      "type": "string"
    },
    "repos": {
      "description": "array of repositories which has this AIP",
      "type": "array",
      "items": { "type": "string" },
      "minItems": 1
    },
    "reposManifestDate": {
      "allOf": [
        {
          "$ref": "./_util.schema.json#/definitions/iso8601datetime"
        },
        {
          "description": "date on the AIP manifest. Used to detect when the AIP has been updated, so this date should be stored with any processing."
        }
      ]
    },
    "reposDate": {
      "allOf": [
        {
          "$ref": "./_util.schema.json#/definitions/iso8601datetime"
        },
        {
          "description": "date when the above two fields were filled in."
        }
      ]
    },
    "METS": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "path": { "type": "string" },
          "md5": { "type": "string", "pattern": "^[0-9a-f]{32}$" }
        }
      }
    },
    "METSManifestDate": {
      "allOf": [
        {
          "$ref": "./_util.schema.json#/definitions/iso8601datetime"
        },
        {
          "description": "date on the AIP manifest when this field was filled in"
        }
      ]
    },
    "METSDate": {
      "allOf": [
        {
          "$ref": "./_util.schema.json#/definitions/iso8601datetime"
        },
        {
          "description": "date when the above two fields were filled in."
        }
      ]
    },
    "updated": {
      "allOf": [
        {
          "$ref": "./_util.schema.json#/definitions/iso8601datetime"
        },
        {
          "description": "date when this document was last updated"
        }
      ]
    }
  },
  "required": [
    "repos",
    "reposManifestDate",
    "reposDate",
    "METS",
    "METSManifestDate",
    "METSDate",
    "updated"
  ]
}

=== crkn-rcdr/Access-Platform/services/couchdb/dipstaging/fixtures/oocihm.8_06941.json
{
  "_id": "oocihm.8_06941",
  "repos": ["eclipse", "swift", "romano"],
  "reposManifestDate": "2016-03-09T18:12:05Z",
  "reposDate": "2021-04-01T22:20:02Z",
  "updated": "2021-04-01T22:20:02Z",
  "METS": [
    {
      "md5": "7d682dcec13c131d72c20c84b2b77fe3",
      "path": "data/revisions/20160309T174453.partial/metadata.xml"
    },
    {
      "path": "data/sip/data/metadata.xml",
      "md5": "6ff6b39d66a6493e4073f5909b8ca32c"
    }
  ],
  "METSManifestDate": "2016-03-09T18:12:05Z",
  "METSDate": "2019-08-29T19:45:32Z",
  "slug": "oocihm.8_06941"
}
