=== crkn-rcdr/Access-Platform/packages/data/schemas/couch/dipstaging.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "/couch/dipstaging",
  "title": "Dipstaging",
  "description": "A document in the `dipstaging` Couch database.",
  "type": "object",
  "properties": {
    "_id": {
      "type": "string"
    },
    "_rev": {
      "description": "The CouchDB revision string for this document. If it doesn't have one, it has yet to be inserted into CouchDB.",
      "type": "string",
      "nullable": true
    },
    "slug": {
      "type": "string",
      "format": "slug",
      "nullable": true,
      "description": "Human-readable identifier used to retrieve this object. Any such object without a slug will not be retrievable without access to the object's Noid."
    },
    "repos": {
      "description": "Array of repositories which has this AIP",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "reposManifestDate": {
      "oneOf": [
        {
          "description": "Number of seconds after the Unix epoch",
          "type": "number"
        },
        {
          "description": "An ISO 6801 timestamp akin to JSON Schema's `date-time`, but only accepts times in UTC. Note that decimal places after the number of seconds are not allowed.",
          "type": "string",
          "pattern": "^\\d{4}-(?:0\\d|1[0-2])-(?:[0-2]\\d|3[0-1])T[0-2]\\d:[0-5]\\d:(?:[0-5]\\d|60)Z$"
        }
      ],
      "description": "Date on the AIP manifest. Used to detect when the AIP has been updated, so this date should be stored with any processing."
    },
    "reposDate": {
      "oneOf": [
        {
          "description": "Number of seconds after the Unix epoch",
          "type": "number"
        },
        {
          "description": "An ISO 6801 timestamp akin to JSON Schema's `date-time`, but only accepts times in UTC. Note that decimal places after the number of seconds are not allowed.",
          "type": "string",
          "pattern": "^\\d{4}-(?:0\\d|1[0-2])-(?:[0-2]\\d|3[0-1])T[0-2]\\d:[0-5]\\d:(?:[0-5]\\d|60)Z$"
        }
      ],
      "description": "Date when the above two fields were filled in."
    },
    "METS": {
      "type": "array",
      "items": {
        "$comment": "METS is the Metadata Encoding and Transmission Standard, which is applied to encoding metadata via a standardized XML schema. METS handles all types of metadata that is relevant to preservation: descriptive, administrative, and technical/structural metadata are all included in the schema, and a METS document will serve as the container for all of this information about a digital object.",
        "title": "Mets",
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "format": "unixFilePath",
            "description": "Path to the file in the legacy preservation repository."
          },
          "md5": {
            "type": "string",
            "description": "MD5 checksum.",
            "pattern": "^[0-9a-f]{32}$"
          }
        }
      },
      "description": "An array of METS data for the document."
    },
    "METSManifestDate": {
      "oneOf": [
        {
          "description": "Number of seconds after the Unix epoch",
          "type": "number"
        },
        {
          "description": "An ISO 6801 timestamp akin to JSON Schema's `date-time`, but only accepts times in UTC. Note that decimal places after the number of seconds are not allowed.",
          "type": "string",
          "pattern": "^\\d{4}-(?:0\\d|1[0-2])-(?:[0-2]\\d|3[0-1])T[0-2]\\d:[0-5]\\d:(?:[0-5]\\d|60)Z$"
        }
      ],
      "description": "Date on the AIP manifest when this field was filled in"
    },
    "METSDate": {
      "oneOf": [
        {
          "description": "Number of seconds after the Unix epoch",
          "type": "number"
        },
        {
          "description": "An ISO 6801 timestamp akin to JSON Schema's `date-time`, but only accepts times in UTC. Note that decimal places after the number of seconds are not allowed.",
          "type": "string",
          "pattern": "^\\d{4}-(?:0\\d|1[0-2])-(?:[0-2]\\d|3[0-1])T[0-2]\\d:[0-5]\\d:(?:[0-5]\\d|60)Z$"
        }
      ],
      "description": "Date when the above two fields were filled in."
    },
    "updated": {
      "oneOf": [
        {
          "description": "Number of seconds after the Unix epoch",
          "type": "number"
        },
        {
          "description": "An ISO 6801 timestamp akin to JSON Schema's `date-time`, but only accepts times in UTC. Note that decimal places after the number of seconds are not allowed.",
          "type": "string",
          "pattern": "^\\d{4}-(?:0\\d|1[0-2])-(?:[0-2]\\d|3[0-1])T[0-2]\\d:[0-5]\\d:(?:[0-5]\\d|60)Z$"
        }
      ],
      "description": "Date when this document was last updated"
    },
    "smelt": {
      "title": "Process update",
      "description": "Trigger for and result of running Smelter on this AIP.",
      "type": "object",
      "properties": {
        "requestDate": {
          "oneOf": [
            {
              "description": "Number of seconds after the Unix epoch",
              "type": "number"
            },
            {
              "description": "An ISO 6801 timestamp akin to JSON Schema's `date-time`, but only accepts times in UTC. Note that decimal places after the number of seconds are not allowed.",
              "type": "string",
              "pattern": "^\\d{4}-(?:0\\d|1[0-2])-(?:[0-2]\\d|3[0-1])T[0-2]\\d:[0-5]\\d:(?:[0-5]\\d|60)Z$"
            }
          ],
          "description": "Most recent request time for the automated process to run."
        },
        "processDate": {
          "oneOf": [
            {
              "description": "Number of seconds after the Unix epoch",
              "type": "number"
            },
            {
              "description": "An ISO 6801 timestamp akin to JSON Schema's `date-time`, but only accepts times in UTC. Note that decimal places after the number of seconds are not allowed.",
              "type": "string",
              "pattern": "^\\d{4}-(?:0\\d|1[0-2])-(?:[0-2]\\d|3[0-1])T[0-2]\\d:[0-5]\\d:(?:[0-5]\\d|60)Z$"
            }
          ],
          "description": "Most recent time the process update took place."
        },
        "succeeded": {
          "type": "boolean",
          "nullable": true,
          "description": "Whether the last process was run successfully on this object."
        },
        "message": {
          "type": "string",
          "nullable": true,
          "description": "Error message supplied by the process."
        }
      },
      "required": [
        "requestDate"
      ],
      "additionalProperties": false
    },
    "staff": {
      "$comment": "Represents data for when a staff member 9user) updates an object, and when they had done so.",
      "title": "StaffUpdate",
      "type": "object",
      "properties": {
        "by": {
          "$comment": "Represents a person who uses the platform.",
          "title": "User",
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "A non-empty string holding the user's name.",
              "pattern": "^.+$"
            },
            "email": {
              "type": "string",
              "description": "A non-empty string with an '@' symbol, holding the user's email.",
              "pattern": "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$"
            }
          },
          "required": [
            "name",
            "email"
          ],
          "description": "The user who has performed the update."
        },
        "date": {
          "oneOf": [
            {
              "description": "Number of seconds after the Unix epoch",
              "type": "number"
            },
            {
              "description": "An ISO 6801 timestamp akin to JSON Schema's `date-time`, but only accepts times in UTC. Note that decimal places after the number of seconds are not allowed.",
              "type": "string",
              "pattern": "^\\d{4}-(?:0\\d|1[0-2])-(?:[0-2]\\d|3[0-1])T[0-2]\\d:[0-5]\\d:(?:[0-5]\\d|60)Z$"
            }
          ],
          "description": "A timestamp showing when the user performed the update."
        }
      },
      "required": [
        "by",
        "date"
      ],
      "description": "A record indicating who last updated the document and when."
    }
  },
  "required": [
    "_id",
    "repos",
    "reposManifestDate",
    "reposDate",
    "METS",
    "METSManifestDate",
    "METSDate",
    "updated"
  ],
  "additionalProperties": false
}

=== crkn-rcdr/Access-Platform/services/couchdb/dipstaging/fixtures/success.json
{
  "_id": "success",
  "_rev": "80-4bc295f01a043397ce34c490154c2161",
  "repos": ["toma", "swift", "romano", "eclipse"],
  "reposManifestDate": "2016-03-08T21:45:41Z",
  "reposDate": "2020-06-02T15:20:19Z",
  "updated": "2020-06-02T15:20:19Z",
  "METS": [
    {
      "md5": "0b488a2ed74b77eee5854c3ac942cdf9",
      "path": "data/revisions/20160308T212400.partial/metadata.xml"
    },
    {
      "md5": "3874ae6f0e72c7798ac63d2070d65826",
      "path": "data/sip/data/metadata.xml"
    }
  ],
  "METSManifestDate": "2016-03-08T21:45:41Z",
  "METSDate": "2019-08-29T19:45:37Z",
  "slug": "success",
  "smelt": {
    "succeeded": true,
    "message": "test",
    "requestDate": "2020-04-20T20:28:52Z",
    "processDate": "2020-04-22T21:01:24Z"
  }
}
