=== crkn-rcdr/Access-Platform/data/schemas/couch/canvas.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "/couch/canvas",
  "title": "Canvas",
  "type": "object",
  "description": "A document in the `canvas` Couch database.",
  "properties": {
    "_id": {
      "type": "string",
      "format": "noid",
      "description": "This resource's Noid. It's a unique, opaque identifier."
    },
    "_rev": {
      "description": "The CouchDB revision string for this document. If it doesn't have one, it has yet to be inserted into CouchDB.",
      "type": "string",
      "nullable": true
    },
    "public": {
      "type": "string",
      "format": "timestamp",
      "nullable": true,
      "description": "If set, the object was made available to the public at this time. If unset, it is not available to the public."
    },
    "updated": {
      "type": "string",
      "format": "timestamp",
      "nullable": true,
      "description": "Timestamp for when this object was last updated."
    },
    "updateInternalmeta": {
      "title": "Process update",
      "description": "Information about the most recent update to the internalmeta database made because of changes to this object.",
      "type": "object",
      "properties": {
        "requestDate": {
          "type": "string",
          "format": "timestamp",
          "description": "Most recent request time for the automated process to run."
        },
        "processDate": {
          "type": "string",
          "format": "timestamp",
          "nullable": true,
          "description": "Most recent time the process update took place."
        },
        "succeeded": {
          "type": "boolean",
          "nullable": true,
          "description": "Whether the last process was run successfully on this object."
        },
        "message": {
          "type": "string",
          "nullable": true,
          "description": "Error message supplied by the process."
        }
      },
      "required": [
        "requestDate"
      ],
      "additionalProperties": false,
      "nullable": true
    },
    "source": {
      "description": "Information about the preservation source of this base image of this canvas.",
      "type": "object",
      "oneOf": [
        {
          "description": "Source information for an image in the legacy preservation repository.",
          "properties": {
            "from": {
              "type": "string",
              "const": "cihm"
            },
            "path": {
              "type": "string",
              "format": "unixFilePath",
              "description": "Legacy repository path."
            }
          },
          "required": [
            "from",
            "path"
          ],
          "additionalProperties": false
        },
        {
          "description": "Source information for an image in Archivematica.",
          "properties": {
            "from": {
              "type": "string",
              "const": "cihm"
            },
            "aipId": {
              "type": "string"
            },
            "objId": {
              "type": "string"
            }
          },
          "required": [
            "from",
            "aipId",
            "objId"
          ],
          "additionalProperties": false
        }
      ],
      "required": [
        "from"
      ]
    },
    "master": {
      "$comment": "Reference to a stored image, which can be found in either the legacy preservation repository or the access platform file store.",
      "title": "Image file reference",
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "format": "unixFilePath",
          "nullable": true,
          "description": "Path to the file in the legacy preservation repository.",
          "$comment": "Cannot be defined along with `extension`."
        },
        "extension": {
          "type": "string",
          "enum": [
            "jpg",
            "jp2",
            "jpeg",
            "tif",
            "tiff"
          ],
          "nullable": true,
          "description": "Image file extension.",
          "$comment": "Cannot be defined along with `path`."
        },
        "size": {
          "type": "number",
          "minimum": 0,
          "description": "Size of the file, in bytes."
        },
        "mime": {
          "type": "string",
          "enum": [
            "image/jpeg",
            "image/jp2",
            "image/tiff"
          ],
          "description": "RFC 2046 Media Type (formerly MIME)."
        },
        "height": {
          "type": "integer",
          "minimum": 0,
          "nullable": true,
          "description": "Image height, in pixels.",
          "$comment": "Implies that `width` is defined."
        },
        "width": {
          "type": "integer",
          "minimum": 0,
          "nullable": true,
          "description": "Image width, in pixels.",
          "$comment": "Implies that `height` is defined."
        },
        "update": {
          "title": "Process update",
          "description": "Update for the service that supplies dimension information.",
          "type": "object",
          "properties": {
            "requestDate": {
              "type": "string",
              "format": "timestamp",
              "description": "Most recent request time for the automated process to run."
            },
            "processDate": {
              "type": "string",
              "format": "timestamp",
              "nullable": true,
              "description": "Most recent time the process update took place."
            },
            "succeeded": {
              "type": "boolean",
              "nullable": true,
              "description": "Whether the last process was run successfully on this object."
            },
            "message": {
              "type": "string",
              "nullable": true,
              "description": "Error message supplied by the process."
            }
          },
          "required": [
            "requestDate"
          ],
          "additionalProperties": false,
          "nullable": true
        }
      },
      "required": [
        "mime"
      ],
      "dependencies": {
        "height": [
          "width"
        ],
        "width": [
          "height"
        ]
      },
      "oneOf": [
        {
          "required": [
            "path"
          ]
        },
        {
          "required": [
            "extension"
          ]
        }
      ],
      "description": "Reference to the base image file."
    },
    "takedown": {
      "description": "If the canvas has been taken down from public view, this is the reason why.",
      "type": "string",
      "enum": [
        "copyright",
        "privacy"
      ],
      "nullable": true
    },
    "ocrPdf": {
      "$comment": "Reference to a stored file. The location of the file will either be determined by the `path` property, the `extension` property, or the field's key.",
      "title": "File Reference",
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "format": "unixFilePath",
          "nullable": true,
          "description": "Path to the file in the legacy preservation repository."
        },
        "extension": {
          "type": "string",
          "minLength": 1,
          "nullable": true,
          "description": "File extension for something referenced in the access object store."
        },
        "size": {
          "type": "number",
          "minimum": 0
        },
        "mime": {
          "type": "string",
          "pattern": "^\\w+/\\w+$",
          "nullable": true,
          "description": "Size of the file, in bytes."
        },
        "md5": {
          "type": "string",
          "pattern": "^[0-9a-f]{32}$",
          "nullable": true,
          "description": "MD5 checksum."
        }
      },
      "required": [
        "size"
      ],
      "not": {
        "required": [
          "path",
          "extension"
        ]
      },
      "nullable": true,
      "description": "Reference to the PDF file generated by OCR."
    },
    "ocrType": {
      "description": "OCR XML type.",
      "type": "string",
      "enum": [
        "alto",
        "txtmap"
      ],
      "nullable": true
    },
    "orphan": {
      "description": "As time goes on or errors take place, some canvases may no longer be referenced by a manifest. These canvases may be marked as orphans by setting this flag.",
      "type": "boolean",
      "default": false,
      "nullable": true
    }
  },
  "required": [
    "_id",
    "master",
    "source"
  ],
  "additionalProperties": false
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0dz0311c62f.json
{
  "_id": "69429/c0dz0311c62f",
  "_rev": "4-04231637308636c969ffb4da5ac91059",
  "ocrPdf": {
    "extension": "pdf",
    "size": 8707,
    "md5": "44e25e8e6011619d4b5b53d06508788d"
  },
  "source": {
    "from": "cihm",
    "path": "oocihm.45116/data/sip/data/files/oocihm.45116.0007.tif"
  },
  "master": {
    "size": 7537,
    "height": 3590,
    "mime": "image/tiff",
    "width": 2099,
    "md5": "9319858337268aefcbc3e709d137d3f7",
    "extension": "tif"
  },
  "ocrType": "txtmap"
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0rr1pj0kv4w.json
{
  "_id": "69429/c0rr1pj0kv4w",
  "_rev": "1-d04434ef389e7dd9ffac40de9808fd01",
  "ocrType": "alto",
  "ocrPdf": {
    "size": 1372077,
    "path": "oocihm.8_06941_2/data/sip/data/files/0005.pdf"
  },
  "source": {
    "from": "cihm",
    "path": "oocihm.8_06941_2/data/sip/data/files/0005.jpg"
  },
  "master": {
    "height": 4208,
    "path": "oocihm.8_06941_2/data/sip/data/files/0005.jpg",
    "size": 2267104,
    "width": 3464,
    "mime": "image/jpeg"
  }
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c06d5pb4d58z.json
{
  "_id": "69429/c06d5pb4d58z",
  "_rev": "4-1b558a00f1e534b472a5b55eca39254b",
  "ocrType": "txtmap",
  "master": {
    "extension": "tif",
    "md5": "b99a143e7095aef5d1975f2e76ca0930",
    "width": 3131,
    "mime": "image/tiff",
    "size": 790367,
    "height": 3971
  },
  "source": {
    "path": "oocihm.45116/data/sip/data/files/oocihm.45116.0001.tif",
    "from": "cihm"
  },
  "ocrPdf": {
    "size": 774146,
    "md5": "c664514bd68238bca47ee96af26aa7bc",
    "extension": "pdf"
  }
}

=== crkn-rcdr/Access-Platform/couchdb/canvas/fixtures/69429_c0n00zr2z33x.json
{
  "_id": "69429/c0n00zr2z33x",
  "_rev": "1-d48be52157ebaa671b64ca3ab7f0fe98",
  "master": {
    "mime": "image/jpeg",
    "width": 2984,
    "size": 1968137,
    "height": 4192,
    "path": "oocihm.8_06941_2/data/sip/data/files/0006.jpg"
  },
  "source": {
    "from": "cihm",
    "path": "oocihm.8_06941_2/data/sip/data/files/0006.jpg"
  },
  "ocrPdf": {
    "path": "oocihm.8_06941_2/data/sip/data/files/0006.pdf",
    "size": 1251828
  },
  "ocrType": "alto"
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0pg1hk6nq31.json
{
  "_id": "69429/c0pg1hk6nq31",
  "_rev": "4-7f68e0075e3fcf27c6b2c4a1b7a57d5e",
  "ocrType": "txtmap",
  "master": {
    "extension": "tif",
    "width": 2258,
    "md5": "bd1bcfd11ae1777c69236ffd52e00aaa",
    "mime": "image/tiff",
    "height": 3674,
    "size": 86733
  },
  "ocrPdf": {
    "extension": "pdf",
    "md5": "43ec1cb12d18de6019c0d9560a82e48b",
    "size": 88336
  },
  "source": {
    "from": "cihm",
    "path": "oocihm.45116/data/sip/data/files/oocihm.45116.0005.tif"
  }
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0610vs1v70v.json
{
  "_id": "69429/c0610vs1v70v",
  "_rev": "5-2ac85bd2333feea014d41b3e96320d49",
  "ocrPdf": {
    "extension": "pdf",
    "md5": "bc5742709b15d268d4a3f62956f59e09",
    "size": 1181453
  },
  "master": {
    "mime": "image/jpeg",
    "width": 2992,
    "size": 1794509,
    "md5": "acb2a70c57baf5094ad094fbe41eeae7",
    "height": 4160,
    "extension": "jpg"
  },
  "ocrType": "alto",
  "source": {
    "path": "oocihm.8_06941_1/data/sip/data/files/0002.jpg",
    "from": "cihm"
  }
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c08s4jp15g01.json
{
  "_id": "69429/c08s4jp15g01",
  "_rev": "1-c3f6d67432b07339a75dbe3c1157d30f",
  "master": {
    "mime": "image/jpeg",
    "width": 3400,
    "size": 2646837,
    "height": 4192,
    "path": "oocihm.8_06941_2/data/sip/data/files/0001.jpg"
  },
  "ocrPdf": {
    "size": 1628280,
    "path": "oocihm.8_06941_2/data/sip/data/files/0001.pdf"
  },
  "source": {
    "from": "cihm",
    "path": "oocihm.8_06941_2/data/sip/data/files/0001.jpg"
  },
  "ocrType": "alto"
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0j678v3mt8m.json
{
  "_id": "69429/c0j678v3mt8m",
  "_rev": "5-bbf2c762e6f489cb204bd6df64608629",
  "source": {
    "path": "oocihm.8_06941_1/data/sip/data/files/0007.jpg",
    "from": "cihm"
  },
  "ocrPdf": {
    "size": 1221347,
    "extension": "pdf",
    "md5": "176717ba7ee74363c74b8ecb18b3c088"
  },
  "master": {
    "md5": "d8c7a0f074ab91672e0f7470728e67fd",
    "extension": "jpg",
    "width": 3464,
    "mime": "image/jpeg",
    "height": 4208,
    "size": 1936497
  },
  "ocrType": "alto"
}
