=== crkn-rcdr/Access-Platform/data/schemas/couch/canvas.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "/couch/canvas",
  "title": "Canvas",
  "type": "object",
  "description": "A document in the `canvas` Couch database.",
  "properties": {
    "_id": {
      "type": "string",
      "format": "noid",
      "description": "This resource's Noid. It's a unique, opaque identifier."
    },
    "_rev": {
      "description": "The CouchDB revision string for this document. If it doesn't have one, it has yet to be inserted into CouchDB.",
      "type": "string",
      "nullable": true
    },
    "public": {
      "type": "string",
      "format": "timestamp",
      "nullable": true,
      "description": "If set, the object was made available to the public at this time. If unset, it is not available to the public."
    },
    "updated": {
      "type": "string",
      "format": "timestamp",
      "nullable": true,
      "description": "Timestamp for when this object was last updated."
    },
    "updateInternalmeta": {
      "title": "Process update",
      "description": "Information about the most recent update to the internalmeta database made because of changes to this object.",
      "type": "object",
      "properties": {
        "requestDate": {
          "type": "string",
          "format": "timestamp",
          "description": "Most recent request time for the automated process to run."
        },
        "processDate": {
          "type": "string",
          "format": "timestamp",
          "nullable": true,
          "description": "Most recent time the process update took place."
        },
        "succeeded": {
          "type": "boolean",
          "nullable": true,
          "description": "Whether the last process was run successfully on this object."
        },
        "message": {
          "type": "string",
          "nullable": true,
          "description": "Error message supplied by the process."
        }
      },
      "required": [
        "requestDate"
      ],
      "additionalProperties": false,
      "nullable": true
    },
    "source": {
      "description": "Information about the preservation source of this base image of this canvas.",
      "type": "object",
      "oneOf": [
        {
          "description": "Source information for an image in the legacy preservation repository.",
          "properties": {
            "from": {
              "type": "string",
              "const": "cihm"
            },
            "path": {
              "type": "string",
              "format": "unixFilePath",
              "description": "Legacy repository path."
            }
          },
          "required": [
            "from",
            "path"
          ],
          "additionalProperties": false
        },
        {
          "description": "Source information for an image in Archivematica.",
          "properties": {
            "from": {
              "type": "string",
              "const": "cihm"
            },
            "aipId": {
              "type": "string"
            },
            "objId": {
              "type": "string"
            }
          },
          "required": [
            "from",
            "aipId",
            "objId"
          ],
          "additionalProperties": false
        }
      ],
      "required": [
        "from"
      ]
    },
    "master": {
      "$comment": "Reference to a stored image, which can be found in either the legacy preservation repository or the access platform file store.",
      "title": "Image file reference",
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "format": "unixFilePath",
          "nullable": true,
          "description": "Path to the file in the legacy preservation repository.",
          "$comment": "Cannot be defined along with `extension`."
        },
        "extension": {
          "type": "string",
          "enum": [
            "jpg",
            "jp2",
            "jpeg",
            "tif",
            "tiff"
          ],
          "nullable": true,
          "description": "Image file extension.",
          "$comment": "Cannot be defined along with `path`."
        },
        "size": {
          "type": "number",
          "minimum": 0,
          "description": "Size of the file, in bytes."
        },
        "mime": {
          "type": "string",
          "enum": [
            "image/jpeg",
            "image/jp2",
            "image/tiff"
          ],
          "description": "RFC 2046 Media Type (formerly MIME)."
        },
        "height": {
          "type": "integer",
          "minimum": 0,
          "nullable": true,
          "description": "Image height, in pixels.",
          "$comment": "Implies that `width` is defined."
        },
        "width": {
          "type": "integer",
          "minimum": 0,
          "nullable": true,
          "description": "Image width, in pixels.",
          "$comment": "Implies that `height` is defined."
        },
        "update": {
          "title": "Process update",
          "description": "Update for the service that supplies dimension information.",
          "type": "object",
          "properties": {
            "requestDate": {
              "type": "string",
              "format": "timestamp",
              "description": "Most recent request time for the automated process to run."
            },
            "processDate": {
              "type": "string",
              "format": "timestamp",
              "nullable": true,
              "description": "Most recent time the process update took place."
            },
            "succeeded": {
              "type": "boolean",
              "nullable": true,
              "description": "Whether the last process was run successfully on this object."
            },
            "message": {
              "type": "string",
              "nullable": true,
              "description": "Error message supplied by the process."
            }
          },
          "required": [
            "requestDate"
          ],
          "additionalProperties": false,
          "nullable": true
        }
      },
      "required": [
        "mime"
      ],
      "dependencies": {
        "height": [
          "width"
        ],
        "width": [
          "height"
        ]
      },
      "oneOf": [
        {
          "required": [
            "path"
          ]
        },
        {
          "required": [
            "extension"
          ]
        }
      ],
      "description": "Reference to the base image file."
    },
    "takedown": {
      "description": "If the canvas has been taken down from public view, this is the reason why.",
      "type": "string",
      "enum": [
        "copyright",
        "privacy"
      ],
      "nullable": true
    },
    "ocrPdf": {
      "$comment": "Reference to a stored file. The location of the file will either be determined by the `path` property, the `extension` property, or the field's key.",
      "title": "File Reference",
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "format": "unixFilePath",
          "nullable": true,
          "description": "Path to the file in the legacy preservation repository."
        },
        "extension": {
          "type": "string",
          "minLength": 1,
          "nullable": true,
          "description": "File extension for something referenced in the access object store."
        },
        "size": {
          "type": "number",
          "minimum": 0
        },
        "mime": {
          "type": "string",
          "pattern": "^\\w+/\\w+$",
          "nullable": true,
          "description": "Size of the file, in bytes."
        },
        "md5": {
          "type": "string",
          "pattern": "^[0-9a-f]{32}$",
          "nullable": true,
          "description": "MD5 checksum."
        }
      },
      "required": [
        "size"
      ],
      "not": {
        "required": [
          "path",
          "extension"
        ]
      },
      "nullable": true,
      "description": "Reference to the PDF file generated by OCR."
    },
    "ocrType": {
      "description": "OCR XML type.",
      "type": "string",
      "enum": [
        "alto",
        "txtmap"
      ],
      "nullable": true
    },
    "orphan": {
      "description": "As time goes on or errors take place, some canvases may no longer be referenced by a manifest. These canvases may be marked as orphans by setting this flag.",
      "type": "boolean",
      "default": false,
      "nullable": true
    }
  },
  "required": [
    "_id",
    "master",
    "source"
  ],
  "additionalProperties": false
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0xk84m9323g.json
{
  "_id": "69429/c0xk84m9323g",
  "_rev": "5-c7926d03748675f8322025b2df88bf6c",
  "ocrType": "alto",
  "source": {
    "path": "oocihm.8_06941_2/data/sip/data/files/0008.jpg",
    "from": "cihm"
  },
  "master": {
    "size": 1363751,
    "md5": "c2d5b83d3b40bd6c4db5578bb2ae9448",
    "height": 4224,
    "width": 2968,
    "extension": "jpg",
    "mime": "image/jpeg"
  },
  "ocrPdf": {
    "extension": "pdf",
    "size": 953240,
    "md5": "2657b647c186ea5dac37e4ea827113be"
  }
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0sq8qd8xc3v.json
{
  "_id": "69429/c0sq8qd8xc3v",
  "_rev": "5-a48cdb81529218c48a94d9024f36fbd8",
  "ocrType": "alto",
  "source": {
    "path": "oocihm.8_06941_1/data/sip/data/files/0005.jpg",
    "from": "cihm"
  },
  "ocrPdf": {
    "size": 1251042,
    "md5": "8050cbbb14c55947c86206d2b72eeeed",
    "extension": "pdf"
  },
  "master": {
    "extension": "jpg",
    "height": 4192,
    "md5": "87ab36c3d85b69f7374d952768fa700d",
    "width": 3160,
    "size": 2058328,
    "mime": "image/jpeg"
  }
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c02b8vd6q98z.json
{
  "_id": "69429/c02b8vd6q98z",
  "_rev": "8-4500555d6838bafe7f42c96561a857ba",
  "source": {
    "path": "oocihm.8_06941_2/data/sip/data/files/0002.jpg",
    "from": "cihm"
  },
  "ocrPdf": {
    "md5": "030cb1323b7a1d5890e8184250c0b646",
    "size": 1021044,
    "extension": "pdf"
  },
  "ocrType": "alto",
  "master": {
    "height": 4208,
    "size": 1534291,
    "width": 2776,
    "extension": "jpg",
    "mime": "image/jpeg",
    "md5": "aa2a3111d024f3fec513c2369399b321"
  }
}

=== crkn-rcdr/Access-Platform/couchdb/canvas/fixtures/69429_c0j678v3mt8m.json
{
  "_id": "69429/c0j678v3mt8m",
  "_rev": "1-f75b16716a980ec51eb4aba5b62f729c",
  "ocrPdf": {
    "path": "oocihm.8_06941_1/data/sip/data/files/0007.pdf",
    "size": 1221347
  },
  "source": {
    "from": "cihm",
    "path": "oocihm.8_06941_1/data/sip/data/files/0007.jpg"
  },
  "master": {
    "height": 4208,
    "size": 1936497,
    "path": "oocihm.8_06941_1/data/sip/data/files/0007.jpg",
    "width": 3464,
    "mime": "image/jpeg"
  },
  "ocrType": "alto"
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0z02z51z77x.json
{
  "_id": "69429/c0z02z51z77x",
  "_rev": "4-fe47e5211e1718d51d6e37f6dcb3bfb8",
  "source": {
    "from": "cihm",
    "path": "oocihm.45116/data/sip/data/files/oocihm.45116.0003.tif"
  },
  "master": {
    "width": 2243,
    "md5": "80145897f6178ce4a8af7b9367e8ef70",
    "extension": "tif",
    "size": 74135,
    "height": 3654,
    "mime": "image/tiff"
  },
  "ocrPdf": {
    "md5": "b2e3a36ecab4401782b726024f827c10",
    "size": 75402,
    "extension": "pdf"
  },
  "ocrType": "txtmap"
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0t727c49g60.json
{
  "_id": "69429/c0t727c49g60",
  "_rev": "4-df3275203987ad512db2f3f3f3ce321a",
  "ocrType": "txtmap",
  "source": {
    "from": "cihm",
    "path": "oocihm.45116/data/sip/data/files/oocihm.45116.0004.tif"
  },
  "master": {
    "extension": "tif",
    "height": 3808,
    "width": 2216,
    "mime": "image/tiff",
    "md5": "e66ea12f319a6108d7f9f21aeea41282",
    "size": 83097
  },
  "ocrPdf": {
    "md5": "99d6aa5f1d6ca27dc32903abf38cd978",
    "extension": "pdf",
    "size": 84435
  }
}

=== crkn-rcdr/Access-Platform/couchdb/canvas/fixtures/69429_c0xg9f66k47d.json
{
  "_id": "69429/c0xg9f66k47d",
  "_rev": "1-6f4a3b5e9dd9a82e37a3fae960e263a9",
  "master": {
    "width": 2992,
    "mime": "image/jpeg",
    "size": 1790490,
    "height": 4192,
    "path": "oocihm.8_06941_1/data/sip/data/files/0004.jpg"
  },
  "ocrPdf": {
    "size": 1154067,
    "path": "oocihm.8_06941_1/data/sip/data/files/0004.pdf"
  },
  "source": {
    "path": "oocihm.8_06941_1/data/sip/data/files/0004.jpg",
    "from": "cihm"
  },
  "ocrType": "alto"
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0cj87k0gq3s.json
{
  "_id": "69429/c0cj87k0gq3s",
  "_rev": "1-18b674cd9826d02b81e29646f6f72afe",
  "ocrType": "alto",
  "ocrPdf": {
    "size": 953240,
    "path": "oocihm.8_06941_2/data/sip/data/files/0008.pdf"
  },
  "source": {
    "path": "oocihm.8_06941_2/data/sip/data/files/0008.jpg",
    "from": "cihm"
  },
  "master": {
    "path": "oocihm.8_06941_2/data/sip/data/files/0008.jpg",
    "height": 4224,
    "size": 1363751,
    "mime": "image/jpeg",
    "width": 2968
  }
}
