=== crkn-rcdr/Access-Platform/data/schemas/couch/canvas.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "/couch/canvas",
  "title": "Canvas",
  "type": "object",
  "description": "A document in the `canvas` Couch database.",
  "properties": {
    "_id": {
      "type": "string",
      "format": "noid",
      "description": "This resource's Noid. It's a unique, opaque identifier."
    },
    "_rev": {
      "description": "The CouchDB revision string for this document. If it doesn't have one, it has yet to be inserted into CouchDB.",
      "type": "string",
      "nullable": true
    },
    "public": {
      "type": "string",
      "format": "timestamp",
      "nullable": true,
      "description": "If set, the object was made available to the public at this time. If unset, it is not available to the public."
    },
    "updated": {
      "type": "string",
      "format": "timestamp",
      "nullable": true,
      "description": "Timestamp for when this object was last updated."
    },
    "updateInternalmeta": {
      "title": "Process update",
      "description": "Information about the most recent update to the internalmeta database made because of changes to this object.",
      "type": "object",
      "properties": {
        "requestDate": {
          "type": "string",
          "format": "timestamp",
          "description": "Most recent request time for the automated process to run."
        },
        "processDate": {
          "type": "string",
          "format": "timestamp",
          "nullable": true,
          "description": "Most recent time the process update took place."
        },
        "succeeded": {
          "type": "boolean",
          "nullable": true,
          "description": "Whether the last process was run successfully on this object."
        },
        "message": {
          "type": "string",
          "nullable": true,
          "description": "Error message supplied by the process."
        }
      },
      "required": [
        "requestDate"
      ],
      "additionalProperties": false,
      "nullable": true
    },
    "source": {
      "description": "Information about the preservation source of this base image of this canvas.",
      "type": "object",
      "oneOf": [
        {
          "description": "Source information for an image in the legacy preservation repository.",
          "properties": {
            "from": {
              "type": "string",
              "const": "cihm"
            },
            "path": {
              "type": "string",
              "format": "unixFilePath",
              "description": "Legacy repository path."
            }
          },
          "required": [
            "from",
            "path"
          ],
          "additionalProperties": false
        },
        {
          "description": "Source information for an image in Archivematica.",
          "properties": {
            "from": {
              "type": "string",
              "const": "cihm"
            },
            "aipId": {
              "type": "string"
            },
            "objId": {
              "type": "string"
            }
          },
          "required": [
            "from",
            "aipId",
            "objId"
          ],
          "additionalProperties": false
        }
      ],
      "required": [
        "from"
      ]
    },
    "master": {
      "$comment": "Reference to a stored image, which can be found in either the legacy preservation repository or the access platform file store.",
      "title": "Image file reference",
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "format": "unixFilePath",
          "nullable": true,
          "description": "Path to the file in the legacy preservation repository.",
          "$comment": "Cannot be defined along with `extension`."
        },
        "extension": {
          "type": "string",
          "enum": [
            "jpg",
            "jp2",
            "jpeg",
            "tif",
            "tiff"
          ],
          "nullable": true,
          "description": "Image file extension.",
          "$comment": "Cannot be defined along with `path`."
        },
        "size": {
          "type": "number",
          "minimum": 0,
          "description": "Size of the file, in bytes."
        },
        "mime": {
          "type": "string",
          "enum": [
            "image/jpeg",
            "image/jp2",
            "image/tiff"
          ],
          "description": "RFC 2046 Media Type (formerly MIME)."
        },
        "height": {
          "type": "integer",
          "minimum": 0,
          "nullable": true,
          "description": "Image height, in pixels.",
          "$comment": "Implies that `width` is defined."
        },
        "width": {
          "type": "integer",
          "minimum": 0,
          "nullable": true,
          "description": "Image width, in pixels.",
          "$comment": "Implies that `height` is defined."
        },
        "update": {
          "title": "Process update",
          "description": "Update for the service that supplies dimension information.",
          "type": "object",
          "properties": {
            "requestDate": {
              "type": "string",
              "format": "timestamp",
              "description": "Most recent request time for the automated process to run."
            },
            "processDate": {
              "type": "string",
              "format": "timestamp",
              "nullable": true,
              "description": "Most recent time the process update took place."
            },
            "succeeded": {
              "type": "boolean",
              "nullable": true,
              "description": "Whether the last process was run successfully on this object."
            },
            "message": {
              "type": "string",
              "nullable": true,
              "description": "Error message supplied by the process."
            }
          },
          "required": [
            "requestDate"
          ],
          "additionalProperties": false,
          "nullable": true
        }
      },
      "required": [
        "mime"
      ],
      "dependencies": {
        "height": [
          "width"
        ],
        "width": [
          "height"
        ]
      },
      "oneOf": [
        {
          "required": [
            "path"
          ]
        },
        {
          "required": [
            "extension"
          ]
        }
      ],
      "description": "Reference to the base image file."
    },
    "takedown": {
      "description": "If the canvas has been taken down from public view, this is the reason why.",
      "type": "string",
      "enum": [
        "copyright",
        "privacy"
      ],
      "nullable": true
    },
    "ocrPdf": {
      "$comment": "Reference to a stored file. The location of the file will either be determined by the `path` property, the `extension` property, or the field's key.",
      "title": "File Reference",
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "format": "unixFilePath",
          "nullable": true,
          "description": "Path to the file in the legacy preservation repository."
        },
        "extension": {
          "type": "string",
          "minLength": 1,
          "nullable": true,
          "description": "File extension for something referenced in the access object store."
        },
        "size": {
          "type": "number",
          "minimum": 0
        },
        "mime": {
          "type": "string",
          "pattern": "^\\w+/\\w+$",
          "nullable": true,
          "description": "Size of the file, in bytes."
        },
        "md5": {
          "type": "string",
          "pattern": "^[0-9a-f]{32}$",
          "nullable": true,
          "description": "MD5 checksum."
        }
      },
      "required": [
        "size"
      ],
      "not": {
        "required": [
          "path",
          "extension"
        ]
      },
      "nullable": true,
      "description": "Reference to the PDF file generated by OCR."
    },
    "ocrType": {
      "description": "OCR XML type.",
      "type": "string",
      "enum": [
        "alto",
        "txtmap"
      ],
      "nullable": true
    },
    "orphan": {
      "description": "As time goes on or errors take place, some canvases may no longer be referenced by a manifest. These canvases may be marked as orphans by setting this flag.",
      "type": "boolean",
      "default": false,
      "nullable": true
    }
  },
  "required": [
    "_id",
    "master",
    "source"
  ],
  "additionalProperties": false
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c02r3nx9kj8p.json
{
  "_id": "69429/c02r3nx9kj8p",
  "_rev": "4-1f8be1bba9a73e7285716f74a4d79f10",
  "master": {
    "mime": "image/tiff",
    "height": 3645,
    "size": 7195,
    "extension": "tif",
    "md5": "c108f21ddf18bc6a50bcf34768056977",
    "width": 2226
  },
  "ocrType": "txtmap",
  "ocrPdf": {
    "extension": "pdf",
    "size": 8218,
    "md5": "e171d15d63f97e6490bb83fb0499e7d4"
  },
  "source": {
    "path": "oocihm.45116/data/sip/data/files/oocihm.45116.0002.tif",
    "from": "cihm"
  }
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0jq0ss90z39.json
{
  "_id": "69429/c0jq0ss90z39",
  "_rev": "4-2dadc61be9811e1968b782b314af24a0",
  "source": {
    "path": "oocihm.45116/data/sip/data/files/oocihm.45116.0006.tif",
    "from": "cihm"
  },
  "master": {
    "md5": "66b96f453c60b5fc653f5f606ace9764",
    "height": 3776,
    "width": 2402,
    "mime": "image/tiff",
    "size": 62825,
    "extension": "tif"
  },
  "ocrPdf": {
    "md5": "aa427a8b916c69ad7452ade5b658d783",
    "extension": "pdf",
    "size": 63836
  },
  "ocrType": "txtmap"
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0jd4pn8zv4m.json
{
  "_id": "69429/c0jd4pn8zv4m",
  "_rev": "8-5acd03a20c3e82a86eb359b116035a70",
  "ocrType": "alto",
  "ocrPdf": {
    "md5": "f36671423f05f9266abd8b74ed9e380a",
    "size": 1251828,
    "extension": "pdf"
  },
  "master": {
    "md5": "0800ab9e52210a1fcd42e0a99be2ddce",
    "mime": "image/jpeg",
    "extension": "jpg",
    "size": 1968137,
    "width": 2984,
    "height": 4192
  },
  "source": {
    "path": "oocihm.8_06941_2/data/sip/data/files/0006.jpg",
    "from": "cihm"
  }
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0dn3zw1b32v.json
{
  "_id": "69429/c0dn3zw1b32v",
  "_rev": "8-098746559f88edb76d4fcdef89ee9f87",
  "source": {
    "path": "oocihm.8_06941_2/data/sip/data/files/0007.jpg",
    "from": "cihm"
  },
  "master": {
    "height": 4192,
    "size": 2167258,
    "width": 3152,
    "extension": "jpg",
    "mime": "image/jpeg",
    "md5": "dae01bf903630c7d2fd67061e27a4133"
  },
  "ocrType": "alto",
  "ocrPdf": {
    "extension": "pdf",
    "size": 1403632,
    "md5": "43f01699456b55738af8afa76770b76e"
  }
}

=== crkn-rcdr/Access-Platform/couchdb/canvas/fixtures/69429_c02805046f82.json
{
  "_id": "69429/c02805046f82",
  "_rev": "1-f1021233a6b16b429577c08dbefb03ae",
  "master": {
    "height": 4160,
    "path": "oocihm.8_06941_1/data/sip/data/files/0003.jpg",
    "size": 1673911,
    "width": 3480,
    "mime": "image/jpeg"
  },
  "source": {
    "path": "oocihm.8_06941_1/data/sip/data/files/0003.jpg",
    "from": "cihm"
  },
  "ocrPdf": {
    "size": 1281330,
    "path": "oocihm.8_06941_1/data/sip/data/files/0003.pdf"
  },
  "ocrType": "alto"
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c0183435vx78.json
{
  "_id": "69429/c0183435vx78",
  "_rev": "10-90b497da11389fe9f26965eaf852b8e5",
  "source": {
    "path": "oocihm.8_06941_2/data/sip/data/files/0003.jpg",
    "from": "cihm"
  },
  "ocrType": "alto",
  "ocrPdf": {
    "extension": "pdf",
    "size": 1312895
  },
  "master": {
    "width": 3264,
    "size": 1999647,
    "extension": "jpg",
    "height": 4208,
    "md5": "50e77dafd5a0a27305395c5532060575",
    "mime": "image/jpeg"
  }
}

=== crkn-rcdr/Access-Platform/services/couchdb/canvas/fixtures/69429_c02805046f82.json
{
  "_id": "69429/c02805046f82",
  "_rev": "7-f0e74d307a04297aed4134dd85a279e0",
  "master": {
    "md5": "0a5157bc03748e14a35c568cb72e7da8",
    "extension": "jpg",
    "height": 4160,
    "mime": "image/jpeg",
    "size": 1673911,
    "width": 3480
  },
  "source": {
    "from": "cihm",
    "path": "oocihm.8_06941_1/data/sip/data/files/0003.jpg"
  },
  "ocrPdf": {
    "md5": "a490f635ca35e8edb3af25f6b57a623f",
    "extension": "pdf",
    "size": 1281330
  },
  "ocrType": "alto"
}

=== crkn-rcdr/Access-Platform/couchdb/canvas/fixtures/69429_c0sq8qd8xc3v.json
{
  "_id": "69429/c0sq8qd8xc3v",
  "_rev": "1-ac518d56ac192e593caf315965969fde",
  "ocrType": "alto",
  "ocrPdf": {
    "path": "oocihm.8_06941_1/data/sip/data/files/0005.pdf",
    "size": 1251042
  },
  "source": {
    "path": "oocihm.8_06941_1/data/sip/data/files/0005.jpg",
    "from": "cihm"
  },
  "master": {
    "width": 3160,
    "mime": "image/jpeg",
    "path": "oocihm.8_06941_1/data/sip/data/files/0005.jpg",
    "height": 4192,
    "size": 2058328
  }
}
