=== crkn-rcdr/Access-Platform/schemas/canvas.full.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "/canvas.json",
  "title": "Canvas",
  "description": "The virtual representation of the space taken up by a page of a Manifest.",
  "type": "object",
  "required": ["master", "source"],
  "oneOf": [{ "required": ["id"] }, { "required": ["_id"] }],
  "properties": {
    "_id": { "$ref": "noid.json" },
    "id": { "$ref": "noid.json" },
    "source": {
      "description": "Information about this canvas's preservation origin",
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "from": {
              "description": "Sourced from legacy Canadiana preservation",
              "const": "cihm"
            },
            "path": { "$ref": "legacyRepoPath.json" }
          },
          "required": ["from", "path"],
          "additionalProperties": false
        },
        {
          "properties": {
            "from": {
              "description": "Sourced from CRKN Archivematica installation",
              "const": "am"
            },
            "aipId": {
              "description": "Archivematica AIP ID",
              "type": "string"
            },
            "objId": {
              "description": "Archivematica Object ID",
              "type": "string"
            }
          },
          "required": ["from", "aipId", "objId"],
          "additionalProperties": false
        }
      ]
    },
    "master": {
      "$comment": "We will be changing this property's name in a forthcoming migration.",
      "description": "Information about this canvas's master image. If path is not specified, a file should exist in the access object store at $id.$extension",
      "type": "object",
      "properties": {
        "mime": { "$ref": "mediaType.json" },
        "size": { "type": "number" },
        "width": { "type": "number" },
        "height": { "type": "number" },
        "update": {
          "description": "Update for the service that checks Cantaloupe for dimension information",
          "$ref": "update.json"
        }
      },
      "required": ["mime", "size"],
      "oneOf": [
        {
          "properties": {
            "path": {
              "$ref": "legacyRepoPath.json"
            }
          },
          "required": ["path"]
        },
        {
          "properties": {
            "extension": {
              "type": "string",
              "enum": ["jpg", "jp2", "jpeg", "tif", "tiff"]
            }
          },
          "required": ["extension"]
        }
      ]
    },
    "takedown": {
      "type": "string",
      "enum": ["copyright", "privacy"]
    },
    "ocrPdf": {
      "description": "Information about the derivative PDF generated by OCR. If path is not specified, a file should exist in the access object store at $id.pdf",
      "type": "object",
      "properties": {
        "path": {
          "$ref": "legacyRepoPath.json"
        },
        "size": { "type": "number" }
      },
      "required": ["size"]
    },
    "ocrType": {
      "description": "The type of the OCR XML data associated with this canvas",
      "type": "string",
      "enum": ["alto", "txtmap"]
    },
    "orphan": {
      "description": "As time goes on or errors take place, some canvases may no longer be referenced by a manifest. These canvases may be marked as orphans by setting this flag.",
      "type": "boolean",
      "default": false
    },
    "updateInternalmeta": {
      "description": "Trigger for updating the manifests that own this canvas in internalmeta, or result of an attempted update",
      "$ref": "update.json"
    }
  },
  "additionalProperties": false
}

=== crkn-rcdr/Access-Platform/Databases/canvas/fixtures/image2.json
{
  "_id": "69429/c0q814m91v8f",
  "ocrType": "txtmap",
  "source": {
    "from": "cihm",
    "path": "ooe.sas_19720816EP/data/sip/data/files/ooe.19720816EP0002.tif"
  },
  "master": {
    "path": "ooe.sas_19720816EP/data/sip/data/files/ooe.19720816EP0002.tif",
    "mime": "image/tiff",
    "size": 48001,
    "width": 2583,
    "height": 3350
  }
}

=== crkn-rcdr/Access-Platform/canvas/fixtures/image1.json
{
  "_id": "69429/c0v11vd6pm9c",
  "ocrType": "txtmap",
  "master": {
    "height": 3350,
    "path": "ooe.sas_19720816EP/data/sip/data/files/ooe.19720816EP0001.jpg",
    "mime": "image/jpeg",
    "width": 2575,
    "size": 433137
  },
  "source": {
    "path": "ooe.sas_19720816EP/data/sip/data/files/ooe.19720816EP0001.jpg",
    "from": "cihm"
  }
}
